### PR TITLE
Add packages for dendrochronology

### PR DESCRIPTION
**Pull request by nfrerebeau**
Add two packages: `dendroNetwork` and `fellingdater`.

### CODE REVIEW

**Comment by bbartholdy** [comment]
To me this seem completely reasonable! I cannot merge since I don't have write access. @benmarwick ?

**Comment by benmarwick** [comment]
Thank you, do you know of any archaeologists using these packages?

**Comment by bbartholdy** [comment]
Maybe @RonaldVisser (the archaeologist who develops the packages) knows this

**Comment by RonaldVisser** [comment]
I developed the package dendroNetwork by converting the scripts of previously published papers into functions. In hindsight, I think I should have developed a package from the start... See also this blog: https://ropensci.org/blog/2024/06/06/from-scripts-to-package/

I hope that people will use the package and I know of some dendro-archaeologist that want to use it. The package is fairly new, so we have to wait...

**Comment by RonaldVisser** [comment]
fellingdater is developed by @hanecakr and also recent. Maybe he knows more?

**Pull request merged**
