### PR TITLE
Add Will et al. 2022

### PR DESCRIPTION
**Pull request by sommergeo**
Hello, Please consider to add this publication.

### CODE REVIEW

**Comment by benmarwick** [comment]
Hi Christian,

Thanks very much for adding this. I had a quick look through the paper, which is very interesting, but I couldn't see where we can find the R code. Can you help me find it? This list is for papers with openly available R code, so we need to confirm that the code is openly available before adding. 

Thank you,

Ben

**Comment by sommergeo** [comment]
Dear Ben,

Thanks for pointing out, I hadn't realized! For some reasons I don't understand the DOI of our public code didn't make it through the editorial process. Sad when it still fails at this point...

Please delete this pull request as the paper does not meet the requirements or paste the DOI of the R Code with the publication: 

R Code: https://doi.org/10.5281/zenodo.6861109

Sorry for the inconvenience!
Best, Chris

**Comment by benmarwick** [comment]
Hi Chris,

Thanks for following up, actually that's fine for this list! I'll add your paper. I didn't know you had all the materials available on Zenodo, that's great to see. Sometimes people post their code and data after the paper is published, so they don't have the DOI at the time the paper is published. Not ideal because the reader of the paper might never know to look beyond the paper for additional materials. But the zenodo archive might show up in a google search, and it has a link back to the a paper, so that's definitely heaps better than nothing!

warmly,

Ben

**Comment by benmarwick** [comment]
Closing the loop: https://twitter.com/archpaperscode/status/1578456238949629975

**Pull request merged**
